name: Deploy to VM

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_IP }}
          username: root
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            cd /root/my-node-app/deploy.sh
